config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :users
    resources :registrations, only: [:new, :create, :edit, :update, :destroy]
  end
  
  resources :users, except: [:new, :create] do
    resources :events
  end
  
  get 'full', to: 'events#full', as: 'full'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get '/auth/google_oauth2/callback', to: 'sessions#google_signin'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  
  get 'password/:id/edit', to: 'users#password_edit', as: 'edit_password'
  patch 'password/:id', to: 'users#password_update', as: "password"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#home'

  get 'info', to: 'application#info'
  get 'safety', to: 'application#safety'
  get 'sunday', to: 'application#sunday'

  get 'onsite', to: 'events#onsite'
  get 'virtual', to: 'events#virtual'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :registrations, dependent: :delete_all
  has_many :events, through: :registrations
  
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  scope :get_name, ->(id) { where(id: id).pluck(:name) }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update ,:destroy, :password_edit, :password_update]
  before_action :redirect_if_not_logged_in, only: [:index, :show, :edit, :update, :destroy, :password_edit, :password_update]
  before_action :redirect_if_not_admin_or_owner, only: [:index, :show, :edit, :update, :destroy, :password_edit, :password_update]

  def index
    if params[:event_id]
      @users = Event.find_by(id: params[:event_id]).users.order(:name)
    else
      @users = User.order(:name)
    end
  end

  def show    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      @alert = "Sign up failed..."
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  def edit
  end

  def update
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.admin = params[:user][:admin]
    if @user.save
      redirect_to @user
    else
      @alert = "Update failed..."
      @errors = @user.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def password_edit
  end

  def password_update
    if params[:user][:password].empty?
      @user.errors.add(:password, message: "must not be blank.")
      @alert = "Password could not be changed."
      @errors = @user.errors.full_messages
      render 'password_edit'
    else
      @user.update(password_params)
      if @user.errors.present?
        @alert = "Password could not be changed."
        @errors = @user.errors.full_messages
        render 'password_edit'
      else
        redirect_to @user, alert: "Password successfully changed."
      end
    end
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def admin_badge
    image_tag "admin.png", alt: "admin", width: "30", height: "25"
  end
end

app/views/users/_form.html.erb
<div class="checkbox mt-4 mb-2">
  <% if current_user && current_user.admin %>
    <label>
      <%= f.check_box :admin %> Check to make this user admin
    </label>
  <% end %>
</div>
<div class="form-floating">
  <%= f.text_field :name, class: "form-control", id: "floatingName", placeholder: "John Doe" %>
  <%= f.label :name, for: "floatingName" %>
</div>
<div class="form-floating">
  <%= f.email_field :email, class: "form-control", id: "floatingEmail", placeholder: "name@example.com" %>
  <%= f.label :email, for: "floatingEmail" %>
</div>

app/views/users/edit.html.erb
<section class="d-flex align-items-center" style="height: 93.5vh; width: 100vw;">
  <main class="form-signin text-center m-auto" style="width: 100%; max-width: 330px; padding: 15px;">

    <% if @alert %>
      <h3><%= @alert %></h3>
        <% @errors.each do |m| %>
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <%= m %><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
    <% end %>

    <%= image_tag "Exilic-Logo-03-Square-Black.png", alt: "logo", width: "75", height: "75" %>
    <h1 class="h3 mb-3 fw-normal">Edit User Info</h1>

    <%= form_for @user do |f| %>
      <%= render partial: 'form', locals: {user: @user, f: f} %>
      <div class="mb-4">
        <%= f.submit "Edit", class:"w-100 btn btn-lg btn-primary" %>
      </div>

      <p><%= link_to "Back to User Info", @user %></p>
    <% end %>

  </main>
</section>

app/views/users/index.html.erb
<div class="d-flex align-items-center mt-5" style="height: 100vh;">
  <div class="m-auto text-center">
    <% if params[:event_id] %>
      <button class="btn btn-outline-dark btn-lg mb-4 px-5 py-3" disabled><h2>Attendees</h2></button>
    <% else %>
      <button class="btn btn-outline-dark btn-lg mb-4 px-5 py-3" disabled><h2>User List</h2></button>
    <% end %>

    <% if @users.empty? %>
      <h3><%= "There is no registered user yet." %></h3>
    <% end %>

    <% @users.each do |user| %>
      <h3 class="lead"><%= link_to user.name, user, class: "btn btn-outline-primary btn-lg"%> <%= admin_badge if user.admin %></h3>      
    <% end %>

    <% if params[:event_id] %>
      <p class="mt-4"><%= link_to "Back to Event", event_path(params[:event_id]) %></p>
    <% else %>
      <p class="mt-4"><%= link_to "Back to Admin", user_path(current_user) %></p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<section class="d-flex align-items-center" style="height: 93.5vh; width: 100vw;">
  <main class="form-signin text-center m-auto" style="width: 100%; max-width: 330px; padding: 15px;">

    <% if @alert %>
      <h3><%= @alert %></h3>
        <% @errors.each do |m| %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <%= m %><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
    <% end %>

    <%= image_tag "Exilic-Logo-03-Square-Black.png", alt: "logo", width: "75", height: "75" %>
    <h1 class="h3 mb-3 fw-normal">Please Sign Up</h1>

    <%= render 'signup_form', user: @user %>

  </main>
</section>

app/views/users/password_edit.html.erb
<section class="d-flex align-items-center" style="height: 93.5vh; width: 100vw;">
  <main class="form-signin text-center m-auto" style="width: 100%; max-width: 330px; padding: 15px;">

    <% if flash[:alert] %>
      <div class="alert alert-warning alert-dismissible fade show mx-auto mb-5" style="width:300px;" role="alert">
        <%= flash[:alert] %><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <% if @alert %>
      <h3><%= @alert %></h3>
        <% @errors.each do |m| %>
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <%= m %><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
    <% end %>

    <%= image_tag "Exilic-Logo-03-Square-Black.png", alt: "logo", width: "75", height: "75" %>
    <h1 class="h3 mb-3 fw-normal">Change Password</h1>

    <%= form_with model: @user, url: password_path(@user) do |f| %>
      <div class="form-floating">
        <%= f.password_field :password, class: "form-control", id: "floatingPassword", placeholder: "**********" %>
        <%= f.label "New Password", for: "floatingPassword" %>
      </div>
      <div class="form-floating">
        <%= f.password_field :password_confirmation, class: "form-control", id: "floatingPasswordConfirmation", placeholder: "Confirm Password" %>
        <%= f.label "Confirm Password", for: "floatingPasswordConfirmation" %>
      </div>
      <div class="mb-4">
        <%= f.submit "Submit", class:"w-100 btn btn-lg btn-primary" %>
      </div>
      
      <p><%= link_to "Back to User Info", @user %></p>
    <% end %>

  </main>
</section>

app/views/users/show.html.erb
<div class="container d-flex align-items-center" style="height: 93.5vh; width: 100vw;">
  <div class="text-center m-auto" style="width: 100%;">
    <% if flash[:alert] %>
      <div class="alert alert-success alert-dismissible fade show mx-auto mb-5" style="width:300px;" role="alert">
        <%= flash[:alert] %><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <h1 class="text-decoration-underline mb-4">User Info</h1>
    <h3>User Name: <%= @user.name %></h3>
    <p class="lead">Email: <%= @user.email %></p>
    <p><small class="muted text-danger fw-bold"><%= '( You are ADMIN )' if @user.admin %></small></p>
    <p><small class="muted"><%= "( Your temporary password is [ #{session[:tmp_password]} ]. Please change your password. )" if session[:tmp_password] %></small></p>
    <%= link_to "Edit User Info", edit_user_path, class: "btn btn-dark mx-2", style: "width: 200px;" %> <%= link_to "Change Password", edit_password_path, class: "btn btn-light mx-2", style: "width: 200px;" %>
    <p>
      <%= link_to "User Events", user_events_path(params[:id]), class: "btn btn-outline-primary btn-lg my-4 mx-2" %>
      <% if current_user.admin && current_user != @user %>
      <%= link_to "Delete User", @user, class: "btn btn-outline-danger btn-lg my-4 mx-2", method: :delete, data: { confirm: 'Are you certain you want to delete this user?' } %>
      <% end %>
    </p>

    <% if current_user.admin %>
      <hr>
      <p>
        <%= link_to "User List", users_path, class: "btn btn-warning btn-lg mt-4 mx-2", style: "width: 200px;" %>
        <%= link_to "Event List", events_path, class: "btn btn-success btn-lg mt-4 mx-2", style: "width: 200px;" %>
      </p>
    <% end %>

  </div>
</div>