config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :users
    resources :registrations, only: [:new, :create, :edit, :update, :destroy]
  end
  
  resources :users, except: [:new, :create] do
    resources :events
  end
  
  get 'full', to: 'events#full', as: 'full'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get '/auth/google_oauth2/callback', to: 'sessions#google_signin'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  
  get 'password/:id/edit', to: 'users#password_edit', as: 'edit_password'
  patch 'password/:id', to: 'users#password_update', as: "password"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#home'

  get 'info', to: 'application#info'
  get 'safety', to: 'application#safety'
  get 'sunday', to: 'application#sunday'

  get 'onsite', to: 'events#onsite'
  get 'virtual', to: 'events#virtual'
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :registrations, dependent: :delete_all
  has_many :users, through: :registrations

  validates_presence_of :title, :date, :time, :description, :spots

  scope :registered?, ->(event, user) { Registration.where("event_id = ? AND user_id = ?", event.id, user.id) }
  scope :onsite_events, ->() { where(onsite: true).order(date: :desc, time: :desc) }
  scope :virtual_events, ->() { where(onsite: false).order(date: :desc, time: :desc) }

  def open?
    if self.spots > 0
      "Remaining Seats: #{self.spots}"
    else
      "The registration for this event is closed."
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update ,:destroy]
  before_action :redirect_if_not_logged_in, only: [:new, :create, :edit, :update, :destroy]
  before_action :redirect_if_not_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    if params[:user_id]
      @events = User.find_by(id: params[:user_id]).events.order(date: :desc, time: :desc)
    else
      @events = Event.all.order(date: :desc, time: :desc)
    end
  end

  def show
    redirect_to events_path if @event.nil?
    @registration = Registration.find_by(event_id: params[:id], user_id: params[:user_id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.toggle(:onsite) if params[:event][:onsite]
    if @event.save
      redirect_to @event, alert: "Event Successfully Created!"
    else
      @alert = "Please fill in all the boxex."
      @errors = @event.errors.full_messages
      render 'new'
    end
  end

  def edit    
  end

  def update    
    @event.update(event_params)
    @event.toggle(:onsite) if (params[:event][:onsite].nil? && @event.onsite) || (params[:event][:onsite] && !@event.onsite)
    if @event.save
      redirect_to @event, alert: "Event Successfully Created!"
    else
      @alert = "Please fill in all the boxex."
      @errors = @event.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  def full
    @events = Event.all.select {|event| event.open?.include?("closed")}

    render 'index'
  end

  def onsite
    @events = Event.onsite_events
    @note = "On-Site"
    render "event_type"
  end

  def virtual
    @events = Event.virtual_events
    @note = "Virtual"
    render "event_type"
  end

  private

  def set_event
    @event = Event.find_by(id: params[:id])
  end


  def event_params
    params.require(:event).permit(:title, :date, :time, :spots, :description)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def date_time_display
    "#{@event.date} @ #{@event.time.strftime('%l:%M %p')}"
  end

  def disabled_attr
    'disabled' if (@event.open?.include?("closed") || @event.users.include?(current_user))
  end
end

app/views/events/_form.html.erb
    <%= form_with model: event, role: "group" do |f| %>
      <div>
        <input type="checkbox" name="event[onsite]" class="btn-check" id="btn-check-outlined" autocomplete="off" <%= 'checked' if event.onsite %>>
        <label class="btn btn-outline-warning" for="btn-check-outlined" style="height: 40px; width: 333px;">On_Site?</label>
      </div>
      <div class="form-floating">
        <%= f.date_field :date, class: "form-control", id: "floatingWhen", placeholder: "Date?" %>
      </div>
      <div class="form-floating">
        <%= f.time_field :time, class: "form-control", id: "floatingWhen", placeholder: "Time?" %>
      </div>
      <div class="form-floating">
        <%= f.text_field :title, class: "form-control", id: "floatingTitle", placeholder: "Event Title" %>
        <%= f.label :title, for: "floatingTitle" %>
      </div>
      <div class="form-floating">
        <%= f.number_field :spots, class: "form-control", id: "floatingspots", placeholder: "Available Spots" %>
        <%= f.label :spots, "Available Spots", for: "floatingspots" %>
      </div>
      <div class="form-floating">
        <%= f.text_area :description, class: "form-control", id: "floatingDescription", placeholder: "Event Description", style: "height: 100px;" %>
        <%= f.label :description, for: "floatingDescription" %>
      </div>
      <div>
        <%= f.submit class:"w-100 btn btn-lg btn-primary" %>
      </div>
    <% end %>

app/views/events/edit.html.erb
<section class="d-flex align-items-center" style="height: 93.5vh; width: 100vw;">
  <main class="form-signin text-center m-auto" style="width: 100%; max-width: 363px; padding: 15px;">

    <% if @alert %>
      <h3><%= @alert %></h3>
        <% @errors.each do |m| %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <%= m %><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
    <% end %>

    <%= image_tag "Exilic-Logo-03-Square-Black.png", alt: "logo", width: "75", height: "75" %>
    <h1 class="h3 mb-3 fw-normal">Edit Event</h1>

    <%= render 'form', event: @event %>

    <p class="mt-3">
      <%= link_to "Back to List", events_path %>
    </p>

  </main>
</section>

app/views/events/event_type.html.erb
<div class="container">

<h1 class="text-center mt-5"><%= @note %> Events</h1>
<p class="lead text-center"><%= link_to "Back to List", events_path %></p>

<div class="accordion mb-3" id="accordionExample">
  
  <% @events.each_with_index do |event, i| %>
    
  <div class="accordion-item">
    <h2 class="accordion-header" id="heading_<%=i%>">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_<%=i%>" aria-expanded="false" aria-controls="collapseOne">
        <%= event.title %>
      </button>
    </h2>
    <div id="collapse_<%=i%>" class="accordion-collapse collapse" aria-labelledby="heading_<%=i%>" data-bs-parent="#accordionExample">
      <div class="accordion-body text-center mx-auto gap-5">
        <p>Date: <%= event.date %><%= ' | On-Site' if event.onsite %></p>
        <p><%= event.open? %></p>
        <% if current_user && params[:user_id] %>
          <%= link_to "Show", user_event_path(current_user, event), class: "btn btn-warning btn-lg mx-3 px-5", style: "width: 150px;" %>
        <% else %>
          <%= link_to "Show", event_path(event), class: "btn btn-warning btn-lg mx-3 px-5", style: "width: 150px;" %>
        <% end %>
        <% if current_user && current_user.admin %>
          <button type="button" class="btn btn-dark btn-lg mx-3 px-5" style="width: 150px;">Edit</button>
        <% end %>
      </div>
    </div>
  </div>

  <% end %>

</div>

</div>

app/views/events/index.html.erb
<div class="container">

<h1 class="text-center mt-5 mb-3"><%= "#{User.get_name(params[:user_id]).first}'s " if params[:user_id] %>Event List</h1>

<% if current_user && current_user.admin %>
  <div class="text-center">
    <%= link_to "New Event", new_event_path, class: "btn btn-outline-success btn-lg my-3" %>
  </div>
<% end %>

<% if params[:user_id].nil? %>
  <p class="lead text-center"><%= link_to "On-Site Events", onsite_path %> | <%= link_to "Virtual Events", virtual_path %></p>
<% end %>

<% if @events.empty? %>
  <div class="container text-center mt-5">
    <%= link_to "Look around the events.", events_path, class: "btn btn-outline-primary btn-lg px-5 py-3" %>  
  </div>
<% end %>

<div class="accordion mb-3" id="accordionExample">
  
  <% @events.each_with_index do |event, i| %>
    
  <div class="accordion-item">
    <h2 class="accordion-header" id="heading_<%=i%>">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_<%=i%>" aria-expanded="false" aria-controls="collapseOne">
        <%= event.title %>
      </button>
    </h2>
    <div id="collapse_<%=i%>" class="accordion-collapse collapse" aria-labelledby="heading_<%=i%>" data-bs-parent="#accordionExample">
      <div class="accordion-body text-center mx-auto gap-5">
        <p>Date: <%= event.date %><%= ' | On-Site' if event.onsite %></p>
        <p><%= event.open? %></p>
        <% if params[:user_id] || logged_in? %>
          <%= link_to "Show", user_event_path(current_user, event), class: "btn btn-warning btn-lg mx-3 px-5", style: "width: 150px;" %>
        <% else %>
          <%= link_to "Show", event_path(event), class: "btn btn-warning btn-lg mx-3 px-5", style: "width: 150px;" %>
        <% end %>
        <% if current_user && current_user.admin %>
          <%= link_to "Edit", edit_event_path(event), class: "btn btn-dark btn-lg mx-3 px-5", style: "width: 150px;" %>
          <%= link_to "Delete", event, class: "btn btn-danger btn-lg mx-3 px-5", style: "width: 150px;", method: :delete, data: { confirm: 'Are you certain you want to delete this event?' } %>
        <% end %>
      </div>
    </div>
  </div>

  <% end %>

</div>

</div>

app/views/events/new.html.erb
<section class="d-flex align-items-center" style="height: 93.5vh; width: 100vw;">
  <main class="form-signin text-center m-auto" style="width: 100%; max-width: 363px; padding: 15px;">

    <% if @alert %>
      <h3><%= @alert %></h3>
        <% @errors.each do |m| %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <%= m %><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
    <% end %>

    <%= image_tag "Exilic-Logo-03-Square-Black.png", alt: "logo", width: "75", height: "75" %>
    <h1 class="h3 mb-3 fw-normal">Create Event</h1>

    <%= render 'form', event: @event %>

    <p class="mt-3">
      <%= link_to "Back to List", events_path %>
    </p>

  </main>
</section>

app/views/events/show.html.erb
<% if flash[:alert] %>  
  <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="container text-center my-5">
  <h1 class="my-5">Event Info</h1>
  <div class="alert alert-info" role="alert">
    <h2 class="alert-heading"><%= @event.title %></h2>
    <% if @event.onsite %>
      <code class="fw-bold">[ ON-SITE EVENT ]</code>
    <% else %>
      <code>[ VIRTUAL EVENT ]</code>
    <% end %>
    <p><%= date_time_display %></p>
    <hr>
    <p class="lead mb-0 px-5"><%= @event.description %></p>
    <small class="muted">( <%= @event.open? %><strong><%= ', You are registered for this event.' if @event.users.include?(current_user) %></strong> )</small>
  </div>

  <a href="<%= new_event_registration_path(@event) %>" class="text-decoration-none text-reset <%= disabled_attr %>"><button type="button" class="btn btn-outline-danger btn-lg mt-3 mx-2 px-5" <%= disabled_attr %>>Register</button></a>

  <br>

  <% if logged_in? && params[:user_id] && Event.registered?(@event, current_user).present? %>
    <%= link_to "Edit", edit_event_registration_path(@event, @registration), class: "btn btn-dark btn-lg mt-3 mx-2 px-5", style: "width: 200px;" %>
    <%= link_to "Cancel", event_registration_path(@event, @registration), class: "btn btn-dark btn-lg mt-3 mx-2 px-5", style: "width: 200px;", method: :delete, data: { confirm: 'Are you certain you want to cancel this?' } %>
  <% end %>

  <% if current_user && current_user.admin %>
    <p class="mt-4">
      <%= link_to "Attendees", event_users_path(@event), class: "btn btn-outline-secondary btn-lg px-5" %>
    </p>
  <% end %>
  
  <p class="mt-3">
    <% if current_user %>
      <%= link_to "Back to Your List", user_events_path(current_user) %> | 
    <% end %>
    <%= link_to "Back to All Events", events_path %>
  </p>
</div>