config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :users
    resources :registrations, only: [:new, :create, :edit, :update, :destroy]
  end
  
  resources :users, except: [:new, :create] do
    resources :events
  end
  
  get 'full', to: 'events#full', as: 'full'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get '/auth/google_oauth2/callback', to: 'sessions#google_signin'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  
  get 'password/:id/edit', to: 'users#password_edit', as: 'edit_password'
  patch 'password/:id', to: 'users#password_update', as: "password"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#home'

  get 'info', to: 'application#info'
  get 'safety', to: 'application#safety'
  get 'sunday', to: 'application#sunday'

  get 'onsite', to: 'events#onsite'
  get 'virtual', to: 'events#virtual'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def redirect_if_not_logged_in
    if !current_user
      redirect_to login_path
    end
  end

  def redirect_if_not_admin
    if current_user
      if !current_user.admin
        redirect_back fallback_location: user_path(current_user), alert: "You requested the page only the owner can access."
      end
    end
  end

  # Use only for User model
  def redirect_if_not_admin_or_owner
    if current_user
      if !(self_account? || current_user.admin)
        redirect_back fallback_location: user_path(current_user), alert: "You requested the page only the owner can access."
      end
    end
  end

  # Check if reservation is owned by current user
  def registration_owned?
    if current_user
      current_user == Registration.find_by(id: params[:id]).user
    end
  end

  # Check if accessing user account is current user's
  def self_account?
    if params[:id]
      current_user.id == params[:id].to_i
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<div class="card bg-dark text-white">
  <%= image_tag "daniil-kuzelev-C4G18Paw0d4-unsplash_.jpg", alt: "background" %>
  <div class="card-img-overlay text-center mt-5">

    <% if flash[:alert] %>
      <div class="alert alert-light alert-dismissible fade show mx-auto" style="width:300px;" role="alert">
        <%= flash[:alert] %><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <h1 class="card-title mt-5 mb-3"><strong>Exilic Ἐκκλησία</strong></h1>
    <p class="card-text lead mb-1 fw-normal">Worship Service Booking System</p>
    <p class="card-text lead fw-normal">During COVID-19 Season</p>
    <!--<hr class="my-4">-->
    <p class="mt-4">Stay safe and stay wonderful till we meet again!!!</p>
    <%= link_to "Upcoming Events", events_path, class: "btn btn-warning btn-lg mt-3 px-4" %>
  </div>
</div>

app/views/application/info.html.erb
<div class="card mx-auto my-5" style="width: 60vw;">
  <%= image_tag "Reopening.jpg", alt: "guidelines", class: "card-img-top" %>
  <div class="card-body">
    <h3 class="my-4 text-center">Important Information</h3>
    <h5 class="card-title my-3">1. Why are we reopening now?</h5>
    <p class="card-text mb-3">While Exilic has never been closed, our physical doors have been. However, with cases going down and vaccines going up, we feel that we can finally meet in a safe way without the threat of a third wave. With more corporate knowledge than ever before, and with offices, stores, restaurants, and even MSG re-opening, we feel that we can finally meet in a safe way as an assembly (<em>ekklesia</em>) of believers.</p>
    <h5 class="card-title my-3">2. Can I attend worship every Sunday?</h5>
    <p class="card-text mb-3">Yes. However, if you’ve attended a Sunday on-site service the previous week, we ask that you wait until Tuesday to register for the next Sunday service. This will allow those who have not attended yet to register first. By Tuesday, as long as there are still spots available, you can register for the upcoming Sunday service.</p>
    <h5 class="card-title my-3">3. Will there still be an online worship service?</h5>
    <p class="card-text mb-3">Yes. Our on-site service will be livestreamed on Youtube and those who are not attending will be able to worship with us virtually. By attending the on-site service, attendees are entering an area where audio and video recording occur and consent to the filming and to the release, publication, exhibition, or reproduction of any and all recorded media.</p>
    <h5 class="card-title my-3">4. How can I register?</h5>
    <p class="card-text mb-3">Registration will open Sunday-Friday for the upcoming Sunday service by clicking on the link below which will take you to the registration page.</p>
    <p class="card-text text-center"><small class="text-muted btn btn-link"><a href="<%= sunday_path %>">Sunday Service</a></small> | <small class="text-muted btn btn-link"><a href="<%= events_path %>">Register</a></small></p>
  </div>
</div>

app/views/application/safety.html.erb
<div class="contatiner mx-auto" style="width: 80vw;">

  <%= image_tag "on-site-worship-guidelines.png", alt: "reopening", class: "rounded mx-auto d-block mt-4", style: "width: 60vw;", id: "top" %>

  <h1 class="text-center m-4">WELCOME EXILIC FAMILY!</h1>
  <p>We have been awaiting this day for a long time (a year to be exact)!</p>
  <p><span class="fw-bold">Pre-registration is required and our seating is limited to 50 attendees per service.</span> By completing your registration to attend, you are agreeing to follow all guidelines for COVID-19 safety as outlined below when you check-in for our service.</p>

  <h3 class="mt-4">REGISTRATION</h3>
  <p>Families who live in the same household should register together and sit together. Please register ALL household members who will be attending. Register persons not living in the same household separately. Please cancel your registration if your plans change and you can no longer attend.</p>
  <p>We are unable to offer Exilic Kids or childcare at this time. </p>

  <h3 class="mt-4">BEFORE YOU ARRIVE</h3>
  <p>Please remember to bring a mask and confirm that your temperature is below 100.4F. Check-in will begin 30 minutes prior to the service in the foyer. Please plan on 10 minutes to check-in according to our new safety protocols.</p>

  <h3 class="mt-4">WHAT TO EXPECT WHEN YOU ARRIVE</h3>
  <p>Please use our private entrance to the Stewart Hotel located on 31st Street. There is an elevator for stroller or wheelchair access from our entrance. Elevators are limited to four (4) people at a time, or one household if more than four (4) individuals.</p>

  <h4>Check-in Station</h4>
  <p>Going up the stairs from the 31st St. entrance will take you to our check-in station.</p>
  <ol>
    <li>Your temperature will be taken via a non-touch thermometer before entering.</li>
    <li>One of our volunteers will confirm that you are registered using their own mobile device.</li>
    <li>
      You will need to agree to the following health screening statements:
      <ul>
        <li>I am currently not experiencing any of these symptoms in the last 48 hours: fever, chills or sweats, cough, shortness of breath or difficulty breathing, fatigue, muscle or body aches, headache, new loss of taste or smell, sore throat, congestion or runny nose, nausea or vomiting, and/or diarrhea.</li>
        <li>I have not had any close contact in the last 14 days with someone with a current diagnosis of COVID-19.</li>
        <li>I have not had a positive COVID-19 diagnostic test in the past 14 days.</li>
      </ul>
    </li>
  </ol>

  <h4>Protocols</h4>
  <p>We kindly require that all attendees adhere to these protocols:</p>
  <ul>
    <li>All persons age 2+ must wear a mask/face covering that covers the nose and mouth inside at all times (except during communion and pastors who will remove their masks when speaking).</li>
    <li>Observe physical distancing of six (6) feet between you and non-household individuals.</li>
    <li>There will be no singing in the worship service at this time due to state distancing guidelines.</li>
    <li>You will be escorted to seats in the sanctuary by an usher.</li>
  </ul>
  <p>Questions or concerns? Contact <a href = "mailto: jinook929@gmail.com" class="fw-bold">onsite@exilic.com</a></p>

</div>

<div class="d-grid gap-2 col-6 mx-auto my-4 text-center">
  <a href="#top"><button class="btn btn-outline-info" type="button">Back to Top</button></a>
</div>

app/views/application/sunday.html.erb
<%= image_tag "stewart_hotel.jpg", alt: "hotel", class: "img-fluid", width: "100%vw%" %>

<div class="container text-center mb-5">
  <h1 class="my-5">SUNDAY SERVICE at 10:30am</h1>

  <h3 class="mb-4"><a href="https://www.youtube.com/channel/UCyelJHPMuHQdHbAdPudPwvg" target="_blank">CLICK HERE</a> for our YouTube Channel</h3>

  <p class="lead">Out of an abundance of caution, we will not meet in person for worship until the Easter Sunday, and will continue to stream our services and bulletins online. We encourage you to worship from home and to fully participate as a worshipper of God whether you are at church or at home. You can also search for “<a href="https://www.google.com/search?q=Exilic+Church" target="_blank">Exilic Church</a>” to find our page.</p>
</div>

<div class="container text-center">
  <h3 class="text-decoration-underline mb-3">Location</h3>
  <p class="my-1">STEWART HOTEL (31st St. Entrance)</p>
  <p class="my-1 fst-italic">Fitzgerald Ballroom</p>
  <p class="my-1">371 7th Ave. </p>
  <p class="my-1">New York, NY 10001</p>
  <p class="mt-3 mb-4">
    <a href="https://www.google.com/maps/place/Exilic+Church/@40.7488743,-73.9921096,16.75z/data=!4m5!3m4!1s0x0:0x96283a8de9a93f6!8m2!3d40.748809!4d-73.9919808" target="_blank">
      <%= image_tag "map.png", alt: "map", width: "100%" %>
    </a>
  </p>
</div>